# Generated by Django 4.2.4 on 2023-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
